In [4]:
# pip install numpy==1.21.0 


In [5]:
# pip install scikit-learn==0.24.2

In [6]:
#import  pandas
import pandas as pd

In [7]:
# import preprocessed_dataset.csv
df=pd.read_csv('preprocessed_dataset.csv')

In [8]:
#first usual command in EDA by (.info) method

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 37 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Unnamed: 0                           90 non-null     int64  
 1   FlightNumber                         90 non-null     int64  
 2   PayloadMass                          90 non-null     float64
 3   Flights                              90 non-null     int64  
 4   GridFins                             90 non-null     int64  
 5   Reused                               90 non-null     int64  
 6   Legs                                 90 non-null     int64  
 7   Block                                90 non-null     float64
 8   ReusedCount                          90 non-null     int64  
 9   Class                                90 non-null     int64  
 10  Orbit_ES-L1                          90 non-null     bool   
 11  Orbit_GEO                         

Unnamed: 0  FlightNumber  PayloadMass  Flights  GridFins  Reused  Legs  \
0           0             1  6104.959412        1         0       0     0   
1           1             2   525.000000        1         0       0     0   
2           2             3   677.000000        1         0       0     0   
3           3             4   500.000000        1         0       0     0   
4           4             5  3170.000000        1         0       0     0   

   Block  ReusedCount  Class  ...  Outcome_None ASDS  Outcome_None None  \
0    1.0            0      0  ...              False               True   
1    1.0            0      0  ...              False               True   
2    1.0            0      0  ...              False               True   
3    1.0            0      0  ...              False              False   
4    1.0            0      0  ...              False               True   

   Outcome_True ASDS  Outcome_True Ocean  Outcome_True RTLS  \
0              False               False              False   
1              False               False              False   
2              False               False              False   
3              False               False              False   
4              False               False              False   

   LandingPad_5e9e3032383ecb267a34e7c7  LandingPad_5e9e3032383ecb554034e7c9  \
0                                False                                False   
1                                False                                False   
2                                False                                False   
3                                False                                False   
4                                False                                False   

   LandingPad_5e9e3032383ecb6bb234e7ca  LandingPad_5e9e3032383ecb761634e7cb  \
0                                False                                False   
1                                False                                False   
2                                False                                False   
3                                False                                False   
4                                False                                False   

   LandingPad_5e9e3033383ecbb9e534e7cc  
0                                False  
1                                False  
2                                False  
3                                False  
4                                False  

[5 rows x 37 columns]

In [9]:
# split our data set to X and y:

X=df.drop('Class', axis=1)
y=df['Class']

In [10]:
# pip install sklearn
from sklearn.model_selection import train_test_split

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X,
                                                      y, test_size=0.20,
                                                       random_state=101)

In [12]:
# K nearest Neighbors classification algorithm
from sklearn.neighbors import KNeighborsClassifier

In [13]:
knn=KNeighborsClassifier(n_neighbors=10)


In [14]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [15]:
prediction=knn.predict(X_test)

  Using cached numpy-1.21.0.zip (10.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Failed to build numpy


  error: subprocess-exited-with-error
  
  exit code: 1
  
  [206 lines of output]
  setup.py:63: RuntimeWarning: NumPy 1.21.0 may not yet support Python 3.11.
    warnings.warn(
  Running from numpy source directory.
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\bit_generator.pyx
  Processing numpy/random\mtrand.pyx
  Processing numpy/random\_bounded_integers.pyx.in
  Processing numpy/random\_common.pyx
  Processing numpy/random\_generator.pyx
  Processing numpy/random\_mt19937.pyx
  Processing numpy/random\_pcg64.pyx
  Processing numpy/random\_philox.pyx
  Processing numpy/random\_sfc64.pyx
  Cythonizing sources
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\ASUS\\anaconda3\\lib', 'C:\\', 'C:\\Users\\ASUS\\anaconda3\\libs']
    NOT AVAILABLE
  
  blis_info:
    libraries blis not found in ['C:\\Users\\ASU

In [16]:
prediction

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'


  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [62 lines of output]
  <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Partial import of sklearn during the build process.
  <string>:116: DeprecationWarning:
  
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html
  
  
  INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  Traceback (most recent call last):
    File "C:\Users\ASUS\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_proces

In [17]:
y_test

50    0
6     1
51    0
54    1
53    1
69    1
32    1
31    1
21    1
88    1
43    1
47    0
3     0
1     0
74    0
16    1
45    0
25    1
Name: Class, dtype: int64

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
confusion_matrix(y_test,prediction)

array([[2, 5],
       [3, 8]], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_test, prediction,normalize=False)

10.0

In [22]:
accuracy_score(y_test, prediction,normalize=True)

0.5555555555555556

In [23]:
from sklearn.metrics import classification_report

In [24]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.40      0.29      0.33         7
           1       0.62      0.73      0.67        11

    accuracy                           0.56        18
   macro avg       0.51      0.51      0.50        18
weighted avg       0.53      0.56      0.54        18



In [25]:
# there are default parameter behind the methods
# we can change the default parameters in order to get better results
# grid search is one of the method which can e used for this aim

In [26]:
knn_1=KNeighborsClassifier()

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
parameters= {'n_neighbors': [1,2,3,4,5,6,7,8,9,10]}

In [29]:
knn_cv = GridSearchCV(knn_1 , parameters)
knn_cv.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [30]:
# now our model is trained and we can ask the model about the best parameters
print ("tuned hyperparameters : (best parameters)" , knn_cv.best_params_)

tuned hyperparameters : (best parameters) {'n_neighbors': 9}


In [31]:
knn_1 = KNeighborsClassifier(n_neighbors=9)

In [32]:
knn_1.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=9)

In [33]:
prediction=knn_1.predict(X_test)
confusion_matrix(y_test,prediction)

array([[2, 5],
       [2, 9]], dtype=int64)

In [36]:
accuracy_score(y_test, prediction,normalize=False)

11.0

In [34]:
accuracy_score(y_test, prediction,normalize=True)

0.6111111111111112

In [35]:
# as we can see, we have better results